# .github/workflows/build-zram-generator-deb.yml
# This workflow compiles the upstream systemd-zram-generator C project
# and packages it into a .deb file specifically for Ubuntu 20.04.
# It uses a newer GitHub Actions runner (ubuntu-latest) but performs the build
# inside a Docker container running Ubuntu 20.04 to ensure compatibility.
name: Build systemd-zram-generator .deb (Ubuntu 20.04 Target)

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build_deb:
    name: Build .deb for Ubuntu 20.04 Target
    runs-on: ubuntu-latest # Use the latest supported Ubuntu runner

    container:
      image: ubuntu:20.04 # Run all steps inside an Ubuntu 20.04 Docker container
      options: --user root # Ensure commands run as root inside the container

    steps:
      # Step 1: Checkout YOUR workflow repository (always implicitly done)
      - name: Checkout Workflow Repository
        uses: actions/checkout@v4

      # Step 2: Install core tools, including git, in the container
      - name: Install Core Tools and Git in Container
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update -y
          apt install -y git wget tar # Ensure git is available, along with wget/tar
          apt clean
          rm -rf /var/lib/apt/lists/*

      # Step 3: Explicitly clone the systemd/systemd-zram-generator C source
      # We'll clone it, and then check its contents rigorously.
      - name: Clone Canonical systemd-zram-generator C source
        run: |
          # Clean up any potential previous clone attempts or debris
          rm -rf ./systemd-zram-generator-source.tmp || true
          rm -rf ./systemd-zram-generator-source || true

          # Set Git safe.directory for the workspace, critical for actions/checkout in containers
          # and general git operations on mounted volumes.
          git config --global --add safe.directory /__w/${{ github.repository }}/${{ github.repository }}

          # Clone into a temporary directory
          git clone https://github.com/systemd/systemd-zram-generator.git systemd-zram-generator-source.tmp

          # Verify contents of the cloned directory immediately
          echo "Contents of temporary cloned directory (systemd-zram-generator-source.tmp):"
          ls -lF ./systemd-zram-generator-source.tmp
          
          if [ ! -f "./systemd-zram-generator-source.tmp/meson.build" ]; then
            echo "ERROR: meson.build NOT found in temporary clone! Listing content again to confirm:"
            ls -lF ./systemd-zram-generator-source.tmp
            echo "Attempted to clone: https://github.com/systemd/systemd-zram-generator.git"
            echo "This is unexpected. Aborting."
            exit 1
          fi

          # If successful, move contents to final expected location
          mv ./systemd-zram-generator-source.tmp ./systemd-zram-generator-source
        working-directory: ${{ github.workspace }} # Perform clone from the workspace root

      - name: Install Remaining Build Dependencies (Non-interactive)
        # Now this working directory should contain the C source
        working-directory: ./systemd-zram-generator-source
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export TZ="Etc/UTC"

          apt update -y
          apt install -y tzdata build-essential meson ninja-build pkg-config libsystemd-dev debhelper devscripts
          
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata

          apt clean
          rm -rf /var/lib/apt/lists/*

      - name: Debug:Final Check - List Contents of systemd-zram-generator-source
        working-directory: ./systemd-zram-generator-source
        run: |
          echo "Current working directory (pwd): $(pwd)"
          echo "Contents of ./systemd-zram-generator-source (FINAL CHECK):"
          ls -lF
          echo "Full recursive listing:"
          ls -lR . 

      - name: Configure and Build Project
        working-directory: ./systemd-zram-generator-source
        run: |
          echo "Current working directory for Meson setup: $(pwd)"
          if [ ! -f "meson.build" ]; then
            echo "ERROR: meson.build is still missing! This should not happen. Fatal error. Listing current directory contents:"
            ls -lF .
            exit 1
          fi
          meson setup . build --prefix=/usr
          ninja -C build

      - name: Create Debian Package
        working-directory: ./systemd-zram-generator-source
        run: |
          dch --create --package systemd-zram-generator --newversion 1.0.0-${GITHUB_RUN_NUMBER} "GitHub Actions build for Ubuntu 20.04."
          dpkg-buildpackage -b -us -uc

      - name: Find .deb package
        id: find_deb
        run: |
          DEB_FILE=$(find /__w/${{ github.repository }}/ -maxdepth 2 -name "systemd-zram-generator_*.deb" -print -quit)
          if [ -z "$DEB_FILE" ]; then
            echo "Error: .deb file not found in root workspace! Trying source dir as fallback."
            DEB_FILE=$(find /__w/${{ github.repository }}/systemd-zram-generator-source/ -name "systemd-zram-generator_*.deb" -print -quit)
            if [ -z "$DEB_FILE" ]; then
              echo "Error: .deb file not found anywhere!"
              exit 1
            fi
            echo "Found .deb in source subdirectory (recovered)."
          else
            echo "Found .deb in root workspace (expected)."
          fi
          echo "deb_file=$DEB_FILE" >> $GITHUB_OUTPUT

      - name: Upload Debian Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: systemd-zram-generator-ubuntu2004-deb
          path: ${{ steps.find_deb.outputs.deb_file }}
          retention-days: 7
