# .github/workflows/build-zram-generator-deb.yml
# This workflow compiles the upstream systemd-zram-generator C project
# and packages it into a .deb file specifically for Ubuntu 20.04.
# It uses a newer GitHub Actions runner (ubuntu-latest) but performs the build
# inside a Docker container running Ubuntu 20.04 to ensure compatibility.
name: Build systemd-zram-generator .deb (Ubuntu 20.04 Target)

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub UI

jobs:
  build_deb:
    name: Build .deb for Ubuntu 20.04 Target
    runs-on: ubuntu-latest # Use the latest supported Ubuntu runner

    container:
      image: ubuntu:20.04 # Run all steps inside an Ubuntu 20.04 Docker container
      options: --user root # Ensure commands run as root inside the container

    steps:
      # Step 1: Checkout YOUR workflow repository (where this workflow file lives)
      - name: Checkout Workflow Repository
        uses: actions/checkout@v4

      # Step 2: Install core tools needed for setup and extraction
      - name: Install Core Tools (unzip, git) in Container
        run: |
          export DEBIAN_FRONTEND=noninteractive
          apt update -y
          apt install -y unzip git # Install unzip for artifacts, git for fallback clone
          apt clean
          rm -rf /var/lib/apt/lists/*
          # Crucial for git operations on mounted volumes in containers
          git config --global --add safe.directory /__w/${{ github.repository }}/${{ github.repository }}

      # Step 3: Download the source code from a *previous successful run* of systemd/systemd-zram-generator's CI
      - name: Download systemd-zram-generator Source from Previous Build (using API)
        id: download_source # Assign an ID to this step to refer to its outputs
        uses: actions/github-script@v7
        with:
          script: |
            const { repos } = github.rest;
            const owner = 'systemd';
            const repo = 'systemd-zram-generator';
            const run_id = 9243760431; // *** CRITICAL: REPLACE THIS WITH A REAL workflow_run_id ***

            console.log(`Fetching workflow run artifacts for run_id: ${run_id}`);
            const artifacts = await repos.listWorkflowRunArtifacts({ owner, repo, run_id });

            if (!artifacts.data.artifacts || artifacts.data.artifacts.length === 0) {
              console.log('No artifacts found for this run. Setting output to indicate no download.');
              core.setOutput('artifact_downloaded', 'false');
              return;
            }

            const sourceArtifact = artifacts.data.artifacts.find(artifact => 
              artifact.name.includes('source') || artifact.name.includes('archive') || artifact.name.includes('code') || artifact.name.includes('build')
            );

            const artifactToDownload = sourceArtifact || artifacts.data.artifacts[0]; // Fallback to first if specific not found

            console.log(`Downloading artifact: ${artifactToDownload.name} (ID: ${artifactToDownload.id})`);
            const download = await repos.downloadArtifact({
              owner,
              repo,
              artifact_id: artifactToDownload.id,
              archive_format: 'zip',
            });
            // GitHub Script action automatically extracts content to process.env.GITHUB_WORKSPACE
            // if archive_format is 'zip'.
            core.setOutput('artifact_downloaded', 'true');
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        working-directory: ${{ github.workspace }} # Correct placement: option for the step, not part of 'with'

      # Step 4: Extract the downloaded artifact or fallback to git clone if no artifact was downloaded
      - name: Extract Artifact or Fallback to Git Clone
        # This step runs after the github-script step.
        # It checks if the artifact was downloaded or falls back to git clone.
        run: |
          EXTRACT_DIR="systemd-zram-generator-source" # Target directory for source
          mkdir -p "$EXTRACT_DIR" # Ensure target directory exists

          # Check if the previous step successfully downloaded an artifact
          if [ "${{ steps.download_source.outputs.artifact_downloaded }}" == "true" ]; then
            echo "Artifact ZIP should be in the workspace. Extracting..."
            # Find the downloaded zip file (actions/github-script names it after the artifact ID usually)
            DOWNLOADED_ZIP=$(find ${{ github.workspace }} -maxdepth 1 -name "*.zip" -print -quit)
            if [ -z "$DOWNLOADED_ZIP" ]; then
              echo "ERROR: Downloaded artifact ZIP file not found! Aborting."
              exit 1
            fi

            unzip -o "$DOWNLOADED_ZIP" -d "$EXTRACT_DIR" # Unzip into the target directory

            # The ZIP might contain a top-level directory (e.g., systemd-zram-generator-main/), so move contents up
            EXTRACTED_SUBDIR=$(find "$EXTRACT_DIR" -maxdepth 1 -mindepth 1 -type d -print -quit)
            if [ -n "$EXTRACTED_SUBDIR" ] && [ -f "$EXTRACTED_SUBDIR/meson.build" ]; then
              echo "Moving contents from $EXTRACTED_SUBDIR to $EXTRACT_DIR..."
              mv "$EXTRACTED_SUBDIR"/* "$EXTRACT_DIR"/
              rm -rf "$EXTRACTED_SUBDIR" # Clean up original extracted subdir
            fi
            rm -f "$DOWNLOADED_ZIP" # Clean up the downloaded zip file
            echo "Source extracted from artifact."
          else
            echo "No artifact was downloaded by the previous step. Falling back to direct git clone..."
            rm -rf "$EXTRACT_DIR" || true # Clean up any previous attempts

            echo "Cloning https://github.com/systemd/systemd-zram-generator.git..."
            git clone --depth 1 https://github.com/systemd/systemd-zram-generator.git "$EXTRACT_DIR"

            if [ ! -f "$EXTRACT_DIR/meson.build" ]; then
              echo "ERROR: meson.build NOT found after fallback git clone! Critical failure."
              ls -lF "$EXTRACT_DIR" # List contents for debug
              exit 1
            fi
            echo "Source cloned via fallback Git."
          fi
        working-directory: ${{ github.workspace }} # This runs from the workspace root

      - name: Install Remaining Build Dependencies (Non-interactive)
        # These dependencies are for the zram-generator project itself.
        working-directory: ./systemd-zram-generator-source # This should now contain the C source
        run: |
          export DEBIAN_FRONTEND=noninteractive
          export TZ="Etc/UTC"

          apt update -y
          apt install -y tzdata build-essential meson ninja-build pkg-config libsystemd-dev debhelper devscripts
          
          ln -snf /usr/share/zoneinfo/$TZ /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata

          apt clean
          rm -rf /var/lib/apt/lists/*

      - name: Debug:Final Check - List Contents of systemd-zram-generator-source
        working-directory: ./systemd-zram-generator-source
        run: |
          echo "Current working directory (pwd): $(pwd)"
          echo "Contents of ./systemd-zram-generator-source (FINAL CHECK):"
          ls -lF
          echo "Full recursive listing:"
          ls -lR . 

      - name: Configure and Build Project
        working-directory: ./systemd-zram-generator-source
        run: |
          echo "Current working directory for Meson setup: $(pwd)"
          if [ ! -f "meson.build" ]; then
            echo "ERROR: meson.build is still missing! This should not happen. Fatal error. Listing current directory contents:"
            ls -lF .
            exit 1
          fi
          meson setup . build --prefix=/usr
          ninja -C build

      - name: Create Debian Package
        working-directory: ./systemd-zram-generator-source
        run: |
          dch --create --package systemd-zram-generator --newversion 1.0.0-${GITHUB_RUN_NUMBER} "GitHub Actions build for Ubuntu 20.04."
          dpkg-buildpackage -b -us -uc

      - name: Find .deb package
        id: find_deb
        run: |
          DEB_FILE=$(find /__w/${{ github.repository }}/ -maxdepth 2 -name "systemd-zram-generator_*.deb" -print -quit)
          if [ -z "$DEB_FILE" ]; then
            echo "Error: .deb file not found in root workspace! Trying source dir as fallback."
            DEB_FILE=$(find /__w/${{ github.repository }}/systemd-zram-generator-source/ -name "systemd-zram-generator_*.deb" -print -quit)
            if [ -z "$DEB_FILE" ]; then
              echo "Error: .deb file not found anywhere!"
              exit 1
            fi
            echo "Found .deb in source subdirectory (recovered)."
          else
            echo "Found .deb in root workspace (expected)."
          fi
          echo "deb_file=$DEB_FILE" >> $GITHUB_OUTPUT

      - name: Upload Debian Package as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: systemd-zram-generator-ubuntu2004-deb
          path: ${{ steps.find_deb.outputs.deb_file }}
          retention-days: 7
